### ISSUE TITLE
StorageType std::list compile error

### ISSUE THREAD

**Issue by fksyuan** [PlatONnetwork/PlatON-CDT#111]
add this "platon::StorageType<"list_var"_n, std::list<std::string>>; sList" to  contract compile error.
[list compile  error.txt](https://github.com/PlatONnetwork/PlatON-CDT/files/4228678/list.compile.error.txt)

**Comment by jatel** [comment]
List was not supported by RLP before, the latest version has been supported, please check the latest version.
