### ISSUE TITLE
ubuntu18.04  Compile Error --target=wasm32

### ISSUE THREAD

**Issue by luoyele** [PlatONnetwork/PlatON-CDT#187]
[  1%] Linking CXX executable ../../bin/platon-cpp
[  1%] Built target platon-cpp
[  1%] Building C object libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt.c.o
cc: error: unrecognized command line option ‘--target=wasm32’; did you mean ‘--target-help’?
libraries/libc/CMakeFiles/c.dir/build.make:62: recipe for target 'libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt.c.o' failed
make[2]: *** [libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt.c.o] Error 1
CMakeFiles/Makefile2:263: recipe for target 'libraries/libc/CMakeFiles/c.dir/all' failed
make[1]: *** [libraries/libc/CMakeFiles/c.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by TraceBundy** [comment]
Please confirm that use  [feature/wasm](https://github.com/platonnetwork/platon-cdt/tree/feature/wasm) branch
