### ISSUE TITLE
platon-cpp HelloWorld.cpp  LLVM ERROR: has not value params

### ISSUE THREAD

**Issue by luoyele** [PlatONnetwork/PlatON-CDT#188]
platon-cpp HelloWorld.cpp 
LLVM ERROR: has not value params

PlatON-CDT/example# platon-cpp contract.cpp 
LLVM ERROR: has not value params

**Comment by TraceBundy** [comment]
Please confirm that use  [feature/wasm](https://github.com/platonnetwork/platon-cdt/tree/feature/wasm) branch，build compiler tool
