### ISSUE TITLE
why implement map and array both in storagetype.hpp and in map.hpp 

### ISSUE THREAD

**Issue by Timmy-crypto** [PlatONnetwork/PlatON-CDT#20]
I want to use map in the contract. But I find there are two implement of map.
One is implemented by storage type
https://github.com/PlatONnetwork/PlatON-CDT/blob/master/libraries/platonlib/include/platon/storagetype.hpp#L166
And another one is implemented in db
https://github.com/PlatONnetwork/PlatON-CDT/blob/master/libraries/platonlib/include/platon/db/map.hpp#L38
Same thing with array. So I want't to know why it was implemented twice. Is there something different between them. And what is the difference of their application situation?

Thanks and look forward to your response.

**Comment by woda0109** [comment]
Efficient use of memory, you can read code in-depth understanding.
