### ISSUE TITLE
ubuntu 16.04 build error when follow the documents

### ISSUE THREAD

**Issue by fksyuan** [PlatONnetwork/PlatON-CDT#79]
Building C object CMakeFiles/cmTC_a757f.dir/testCCompiler.c.o
/home/juzhen/pwasm/PlatON-CDT/build/clang_llvm_8.0/bin/clang    -o CMakeFiles/cmTC_a757f.dir/testCCompiler.c.o   -c /home/juzhen/pwasm/PlatON-CDT/build/CMakeFiles/CMakeTmp/testCCompiler.c
/home/juzhen/pwasm/PlatON-CDT/build/clang_llvm_8.0/bin/clang: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/juzhen/pwasm/PlatON-CDT/build/clang_llvm_8.0/bin/clang)
CMakeFiles/cmTC_a757f.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_a757f.dir/testCCompiler.c.o' failed

**Comment by TraceBundy** [comment]
ubuntu 16.04 untested，please use ubuntu 18.04
